# The routes of the project.
#
# Each route describes how an incoming URL is going
# to be processed by Platform.sh.

# Drupal backend
"https://premium.drupal.dk/":
  type: upstream
  upstream: "backend:http"

"https://api.drupal.dk/":
  type: redirect
  to: "https://premium.drupal.dk"

# Drupal frontends
"https://headless.premium.drupal.dk/":
  type: upstream
  upstream: "frontend:http"
